### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by xin-w8023** [YiwenShaoStephen/pychain_example#7]
When I run the mini_librispeech example by default under env pytorch1.6 & cuda10.2, raise me CUDA runtime error, detail as following:
```shell
Traceback (most recent call last):
  File "train.py", line 330, in <module>
    main()
  File "train.py", line 188, in main
    trainloader, model, criterion, optimizer, writer, epoch, use_cuda)
  File "train.py", line 233, in train
    loss = criterion(outputs, output_lengths, graphs)
  File "/root/miniconda3/envs/chain/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/iscsi/wangxin/asr-tools/pychain_example/tools/pychain/pychain/loss.py", line 100, in forward
    den_objf = ChainFunction.apply(x, x_lengths, den_graphs, self.leaky_coefficient)
  File "/iscsi/wangxin/asr-tools/pychain_example/tools/pychain/pychain/loss.py", line 59, in forward
    leaky_coefficient,
RuntimeError: CUDA error: invalid device function
``` 

When I changed the `loss = criterion(outputs, output_lengths, graphs)` to `loss = criterion(outputs.cpu(), output_lengths, graphs)`, it works but time expensive.

Is there any solution to this or am I compiled `pychain` wrong?

**Comment by YiwenShaoStephen** [comment]
I suspect this issue is caused from some mismatch between your CUDA env you compiled with PyTorch and PyChain. My suggestion is to clean your current pychain libs and rebuild it with your recent CUDA and pytorch version.

**Comment by xin-w8023** [comment]
> I suspect this issue is caused from some mismatch between your CUDA env you compiled with PyTorch and PyChain. My suggestion is to clean your current pychain libs and rebuild it with your recent CUDA and pytorch version.

thanks for your reply. I created a brand new conda env and rebuild pychain, but the error still there.
I dive into the code, line 105 in `pytorch_binding/src/chain-computation.cc`

`auto this_alpha = alpha_.narrow(0, 0, batch_size).narrow(1, t, 1).narrow(2, 0, num_states_).squeeze(1)`

when t greater than 0, the program will crash.

**Comment by YiwenShaoStephen** [comment]
@xin-w8023 Have you solved this issue? 
Sorry currently I don't have resources to check it out by myself. It does look like there is some mismatch between your cuda and pychain and I'm afraid you'll probably have to figure it out on your machine by yourself. One thing I can make sure is that pychain is still working properly with pytorch 1.6 and cuda 10.2 on our machines. 
Please let me know if you need any other additional information from my side!

**Comment by xin-w8023** [comment]
> @xin-w8023 Have you solved this issue?
> Sorry currently I don't have resources to check it out by myself. It does look like there is some mismatch between your cuda and pychain and I'm afraid you'll probably have to figure it out on your machine by yourself. One thing I can make sure is that pychain is still working properly with pytorch 1.6 and cuda 10.2 on our machines.
> Please let me know if you need any other additional information from my side!

Sorry that I did not tell you the problem has been solved. I created a new env, and installed pytorch and CUDA with `pip` instead of `conda` and the error disappeared. 
PS: I still confused with it.
